### ISSUE TITLE
[Bug] Cuda Error library ,TVM  Compilation

### ISSUE THREAD

**Issue by Vinaysukhesh98** [mlc-ai/mlc-llm#1434]
## 🐛 Bug

javac error but java paths has been set properly

## To Reproduce

1../preparelib.sh

Make Warning at mlc-llm/CMakeLists.txt:104 (message):
  Cannot find libflash_attn.  The model must not have been built with
  --use-flash-attn-mqa option.

getting below error
-- TVM_HOME: mlc-llm/android/library/../../3rdparty/tvm
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY
  JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindJNI.cmake:382 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:19 (find_package)

## Expected behavior

build done

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):UBUNTU.22
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)Android
 - How you installed MLC-LLM (`conda`, source):conda
 - How you installed TVM-Unity (`pip`, source):source
 - Python version (e.g. 3.10):3.10
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):12
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):python3 -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mbulab5001-linux/.local/lib/python3.10/site-packages/tvm/__init__.py", line 26, in <module>
    from ._ffi.base import TVMError, __version__, _RUNTIME_ONLY
  File "/home/mbulab5001-linux/.local/lib/python3.10/site-packages/tvm/_ffi/__init__.py", line 28, in <module>
    from .base import register_error
  File "/home/mbulab5001-linux/.local/lib/python3.10/site-packages/tvm/_ffi/base.py", line 78, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "/home/mbulab5001-linux/.local/lib/python3.10/site-packages/tvm/_ffi/base.py", line 64, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)

 - Any other relevant information:

## Additional context

/prepare_libs.sh 
+ rustup target add aarch64-linux-android
info: component 'rust-std' for target 'aarch64-linux-android' is up to date
+ mkdir -p build/model_lib
+ python3 prepare_model_lib.py
Creating lib from ['/home/mbulab5001-linux/Documents/Vinay/mlc-llm/dist/Llama-2-7b-chat-hf-q4f16_1/Llama-2-7b-chat-hf-q4f16_1-android.tar']..
+ cd build
+ touch config.cmake
+ '[' /home/mbulab5001-linux/Documents/Vinay/mlc-llm/3rdparty/tvm/ -ne 0 ']'
./prepare_libs.sh: line 12: [: /home/mbulab5001-linux/Documents/Vinay/mlc-llm/3rdparty/tvm/: integer expression expected
+ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/home/mbulab5001-linux/Android/Sdk/ndk/25.2.9519653/build/cmake/android.toolchain.cmake -DCMAKE_INSTALL_PREFIX=. -DCMAKE_CXX_FLAGS=-O3 -DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=android-24 -DANDROID_PLATFORM=android-24 -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ON -DANDROID_STL=c++_static -DUSE_HEXAGON_SDK=OFF -DMLC_LLM_INSTALL_STATIC_LIB=ON -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON -DUSE_OPENCL=ON -DUSE_CUSTOM_LOGGING=ON
-- Hide private symbols
-- TVM_HOME: 3rdparty/tvm
-- Hide private symbols...
-- Forbidding undefined symbols in shared library, using -Wl,--no-undefined on platform Android
-- Building for Android
-- Didn't find the path to CCACHE, disabling ccache
-- VTA build with VTA_HW_PATH=/home/mbulab5001-linux/Documents/Vinay/mlc-llm/3rdparty/tvm/3rdparty/vta-hw
-- Build VTA runtime with target: sim
-- Enabled runtime search for OpenCL library location
-- Couldn't build OpenCL-Gtests
-- Android Vulkan_INCLUDE_DIRS=/home/mbulab5001-linux/Android/Sdk/ndk/25.2.9519653/sources/third_party/vulkan/src/include
-- Skip finding SPIRV in Android, make sure you only build tvm runtime.
-- Build with contrib.random
-- Build with contrib.sort
-- Build with contrib.hybriddump
-- Git found: /usr/bin/git
-- Found TVM_GIT_COMMIT_HASH=5aa839378d4457e528eb8fce2ab1a0295007d9d1
-- Found TVM_GIT_COMMIT_TIME=2023-12-17 12:23:50 -0800
-- Building with TVM Map...
-- Build with thread support...
-- CLANG_VERSION 14.0
-- Setting enhanced clang warning flags
-- Added "-fuse-ld=lld" to linker flags -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments 
-- Build without FlashInfer
-- system-nameAndroid
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- VERSION: 0.2.00
CMake Warning at /home/mbulab5001-linux/Documents/Vinay/mlc-llm/CMakeLists.txt:104 (message):
  Cannot find libflash_attn.  The model must not have been built with
  --use-flash-attn-mqa option.

**Comment by sherelynyap** [comment]
For me, setting it the CMakeList.txt, helped to find JNI

JAVA_AWT_LIBRARY      = the path to the jawt library
JAVA_JVM_LIBRARY      = the path to the jvm library
JAVA_INCLUDE_PATH     = the include path to jni.h
JAVA_INCLUDE_PATH2    = the include path to jni_md.h
JAVA_AWT_INCLUDE_PATH = the include path to jawt.h

e.g.
```
set(JAVA_AWT_LIBRARY "C:/Program Files/Microsoft/jdk-17.0.8.7-hotspot/include/win32")
set(JAVA_JVM_LIBRARY "C:/Program Files/Microsoft/jdk-17.0.8.7-hotspot/include/win32")
set(JAVA_INCLUDE_PATH2 "C:/Program Files/Microsoft/jdk-17.0.8.7-hotspot/include")
set(JAVA_INCLUDE_PATH2 "C:/Program Files/Microsoft/jdk-17.0.8.7-hotspot/include/win32")
set(JAVA_AWT_INCLUDE_PATH "C:/Program Files/Microsoft/jdk-17.0.8.7-hotspot/include")
```

**Comment by Moon-Ahn** [comment]
I faced the same problem, but I solved it.
Please run
```
conda install cmake
``` 

If not, please follow the order below.
```
sudo apt-get install -y openjdk-8-jdk
sudo apt-get install -y default-jdk
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
conda install cmake
```
