### ISSUE TITLE
[Bug] Google Colab T4 Error TVMError: FlashInfer ParallelTopPSamplingFromProb error no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Faolain** [mlc-ai/mlc-llm#2488]
## 🐛 Bug

Currently if you try to modify the Jupyter notebooks in Google Colab such as https://github.com/mlc-ai/notebooks/blob/main/mlc-llm/tutorial_chat_module_getting_started.ipynb or [wizardLM](https://colab.research.google.com/github/mlc-ai/notebooks/blob/main/mlc-llm/models/demo_WizardLM_Math_Coder.ipynb#scrollTo=s6YdYe5AnVzN) and simply modifying the notebooks to support MLCEngine instead of the previous ChatModule: 

```
!nvidia-smi
Sun Jun  2 04:50:40 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

```
!pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly-cu122 mlc-ai-nightly-cu122

!git lfs install

!mkdir -p dist
!git clone https://github.com/mlc-ai/binary-mlc-llm-libs.git dist/prebuilt_libs

!cd dist/prebuilt && git clone && git clone https://huggingface.co/mlc-ai/Llama-3-8B-Instruct-q4f32_1-MLC

from mlc_llm import MLCEngine

engine = MLCEngine(
   model="dist/prebuilt/Llama-3-8B-Instruct-q4f32_1-MLC",
)

output = engine.chat.completions.create(
        messages=[
            {"role": "user", "content": "Give me three American cities names"},
        ]
)
```

## Error Message

```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/usr/local/lib/python3.10/dist-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "/workspace/mlc-llm/cpp/serve/threaded_engine.cc", line 169, in mlc::llm::serve::ThreadedEngineImpl::RunBackgroundLoop()
  File "/workspace/mlc-llm/cpp/serve/engine.cc", line 611, in mlc::llm::serve::EngineImpl::Step()
  File "/workspace/mlc-llm/cpp/serve/engine_actions/new_request_prefill.cc", line 220, in mlc::llm::serve::NewRequestPrefillActionObj::Step(mlc::llm::serve::EngineState)
  File "/workspace/mlc-llm/cpp/serve/sampler/gpu_sampler.cc", line 183, in mlc::llm::serve::GPUSampler::BatchSampleTokensWithProbAfterTopP(tvm::runtime::NDArray, std::vector<int, std::allocator<int> > const&, tvm::runtime::Array<tvm::runtime::String, void> const&, tvm::runtime::Array<mlc::llm::serve::GenerationConfig, void> const&, std::vector<mlc::llm::RandomGenerator*, std::allocator<mlc::llm::RandomGenerator*> > const&)
  File "/workspace/mlc-llm/cpp/serve/sampler/gpu_sampler.cc", line 361, in mlc::llm::serve::GPUSampler::BatchSampleTokensImpl(tvm::runtime::NDArray, std::vector<int, std::allocator<int> > const&, tvm::runtime::Array<tvm::runtime::String, void> const&, tvm::runtime::Array<mlc::llm::serve::GenerationConfig, void> const&, std::vector<mlc::llm::RandomGenerator*, std::allocator<mlc::llm::RandomGenerator*> > const&, bool)
  File "/workspace/mlc-llm/cpp/serve/sampler/gpu_sampler.cc", line 442, in mlc::llm::serve::GPUSampler::ChunkSampleTokensImpl(tvm::runtime::NDArray, std::vector<int, std::allocator<int> > const&, tvm::runtime::Array<mlc::llm::serve::GenerationConfig, void> const&, std::vector<mlc::llm::RandomGenerator*, std::allocator<mlc::llm::RandomGenerator*> > const&, bool)
  File "/workspace/mlc-llm/cpp/serve/sampler/gpu_sampler.cc", line 557, in mlc::llm::serve::GPUSampler::SampleOnGPU(tvm::runtime::NDArray, tvm::runtime::NDArray, tvm::runtime::NDArray, bool, bool, int, std::vector<int, std::allocator<int> > const&)
tvm._ffi.base.TVMError: Traceback (most recent call last):
  10: mlc::llm::serve::ThreadedEngineImpl::RunBackgroundLoop()
        at /workspace/mlc-llm/cpp/serve/threaded_engine.cc:169
  9: mlc::llm::serve::EngineImpl::Step()
        at /workspace/mlc-llm/cpp/serve/engine.cc:611
  8: mlc::llm::serve::NewRequestPrefillActionObj::Step(mlc::llm::serve::EngineState)
        at /workspace/mlc-llm/cpp/serve/engine_actions/new_request_prefill.cc:220
  7: mlc::llm::serve::GPUSampler::BatchSampleTokensWithProbAfterTopP(tvm::runtime::NDArray, std::vector<int, std::allocator<int> > const&, tvm::runtime::Array<tvm::runtime::String, void> const&, tvm::runtime::Array<mlc::llm::serve::GenerationConfig, void> const&, std::vector<mlc::llm::RandomGenerator*, std::allocator<mlc::llm::RandomGenerator*> > const&)
        at /workspace/mlc-llm/cpp/serve/sampler/gpu_sampler.cc:183
  6: mlc::llm::serve::GPUSampler::BatchSampleTokensImpl(tvm::runtime::NDArray, std::vector<int, std::allocator<int> > const&, tvm::runtime::Array<tvm::runtime::String, void> const&, tvm::runtime::Array<mlc::llm::serve::GenerationConfig, void> const&, std::vector<mlc::llm::RandomGenerator*, std::allocator<mlc::llm::RandomGenerator*> > const&, bool)
        at /workspace/mlc-llm/cpp/serve/sampler/gpu_sampler.cc:361
  5: mlc::llm::serve::GPUSampler::ChunkSampleTokensImpl(tvm::runtime::NDArray, std::vector<int, std::allocator<int> > const&, tvm::runtime::Array<mlc::llm::serve::GenerationConfig, void> const&, std::vector<mlc::llm::RandomGenerator*, std::allocator<mlc::llm::RandomGenerator*> > const&, bool)
        at /workspace/mlc-llm/cpp/serve/sampler/gpu_sampler.cc:442
  4: mlc::llm::serve::GPUSampler::SampleOnGPU(tvm::runtime::NDArray, tvm::runtime::NDArray, tvm::runtime::NDArray, bool, bool, int, std::vector<int, std::allocator<int> > const&)
        at /workspace/mlc-llm/cpp/serve/sampler/gpu_sampler.cc:557
  3: _ZN3tvm7runtime13PackedFuncObj9ExtractorINS0_1
  2: tvm::runtime::TypedPackedFunc<void (DLTensor*, DLTensor*, DLTensor*, DLTensor*)>::AssignTypedLambda<void (*)(DLTensor*, DLTensor*, DLTensor*, DLTensor*)>(void (*)(DLTensor*, DLTensor*, DLTensor*, DLTensor*), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*) const
  1: _FlashInferParallelSamplingFromProb(DLTensor*, DLTensor*, DLTensor*, DLTensor*)
  0: _ZN3tvm7runtime6deta
  File "/workspace/tvm/3rdparty/flashinfer/src/tvm_wrapper.cu", line 716
TVMError: FlashInfer ParallelTopPSamplingFromProb error no kernel image is available for execution on the device
```

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): T4 CUDA on Google Colab
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
PRETTY_NAME="Ubuntu 22.04.3 LTS"
```
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): T4
 - How you installed MLC-LLM (`conda`, source): pip in colab
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by MasterJH5574** [comment]
Hi @Faolain, we have fixed this in #2502. It takes a day for the nightly pip package to build and update. Would you mind trying again on Colab tomorrow?

**Comment by Faolain** [comment]
Will do!

**Comment by MasterJH5574** [comment]
@Faolain I just quickly checked on Colab and it can give me three US city names:
```
ChatCompletionResponse(id='chatcmpl-8d65b38b10a64e76b6fabaa3a93f022d', choices=[ChatCompletionResponseChoice(finish_reason='stop', index=0, message=ChatCompletionMessage(content='Here are three American city names:\n\n1. New York City\n2. Los Angeles\n3. Chicago', role='assistant', name=None, tool_calls=None, tool_call_id=None), logprobs=None)], created=1717596237, model=None, system_fingerprint='', object='chat.completion', usage=CompletionUsage(completion_tokens=21, prompt_tokens=32, total_tokens=53, extra={'num_input_tokens': 32, 'num_prefill_tokens': 32, 'num_output_tokens': 21, 'decode_tokens_per_s': 25.203583354748474, 'prefill_tokens_per_s': 73.97731123724442, 'end_to_end_latency_s': 1.2657799120000002}))
```

**Comment by Faolain** [comment]
Confirmed works! Closing the issue thanks again!
